name: Aggiorna GirettiMap

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 curl-cffi

      - name: Run script aggiorna-giri.py
        run: |
          python3 girettimap/aggiorna-giri.py

      - name: Commit file e immagini
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add girettimap/
          
          # Metodo infallibile: controlla se ci sono file modificati tramite 'porcelain'
          if [ -n "$(git status --porcelain)" ]; then
            echo "Modifiche rilevate, procedo al commit..."
            git commit -m "Aggiornamento automatico giri.js e anteprime"
            git push
          else
            echo "Nessuna modifica da committare. Tutto aggiornato!"
          fi